import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import stylesvilla from '../styles/article.module.css';


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Les2 Immobilier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <main className={stylesvilla.main}>
        {/* <div className={styles.grid}> */}
          {/* <Article name='Villa "Stark"' prix={10_000_000} adresse="Malibu, California" photo="https://i.pinimg.com/originals/f1/7a/09/f17a09db50bc69d3ae1708b1bf2ccb87.png"/> */}
        {/* </div> */}
        <div className={stylesvilla.diveng}>
            <span id={stylesvilla.Name}>Villa Stark</span>
            <span id={stylesvilla.Adresse}>Malibu, California</span>
            <span id={stylesvilla.Prix}>{new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'USD' }).format(10_000_000)}</span>
        </div>
          <div>
            <img className={stylesvilla.img} src="https://i.pinimg.com/originals/f1/7a/09/f17a09db50bc69d3ae1708b1bf2ccb87.png" width="832" height="600"></img>
          </div>
        
      </main>
    </div>
  )
}

export default Home
