import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Villa from '../components/Villa/villa'
type props = {
  articles: article[]
}
const Home = ({ articles }: props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Les2 Immobilier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <main id="titre" className={styles.main}>
        <h1 className={styles.title}>
          Bienvenue sur <span style={{ color: "var(--accent-color)" }}>Les2!</span>
        </h1>
        <div className={styles.grid}>
          <Villa id={"1"} name='Villa "Stark"' prix={"1000€"} adresse="Malibu, California" photo="https://i.pinimg.com/originals/f1/7a/09/f17a09db50bc69d3ae1708b1bf2ccb87.png" />
          <Villa id={"2"} name='Villa "The One"' prix={"1000€"} adresse="Bel Air, Los Angeles" photo="https://4.bp.blogspot.com/-B6ruhrpXKbc/XxnadnE49qI/AAAAAAAB-FY/X_oEH6JHPb0M0TFnqK2WIizR0KvrHCsWwCLcBGAsYHQ/s1600-rw/23%2BPhotos%2Bvs.%2B%2524500%252C000%252C000%2B%2BBel%2BAir%2BMega%2BMansion%2B%2BLos%2BAngeles%2B-%2BLuxury%2BHome%2B%2526%2BInterior%2BDesign%2BTour%2B%25281%2529.PNG" />
          <Villa id={"3"} name='Villa "Navarre"' prix={"1000€"} adresse="Pau, France" photo="https://media.abcsalles.com/images/1/salles/1440x960/508567/villa-navarre-7.jpg" />
          <Villa id={"2"} name='Villa "The One"' prix={"1000€"} adresse="Bel Air, Los Angeles" photo="https://4.bp.blogspot.com/-B6ruhrpXKbc/XxnadnE49qI/AAAAAAAB-FY/X_oEH6JHPb0M0TFnqK2WIizR0KvrHCsWwCLcBGAsYHQ/s1600-rw/23%2BPhotos%2Bvs.%2B%2524500%252C000%252C000%2B%2BBel%2BAir%2BMega%2BMansion%2B%2BLos%2BAngeles%2B-%2BLuxury%2BHome%2B%2526%2BInterior%2BDesign%2BTour%2B%25281%2529.PNG" />
          <Villa id={"3"} name='Villa "Navarre"' prix={"1000€"} adresse="Pau, France" photo="https://media.abcsalles.com/images/1/salles/1440x960/508567/villa-navarre-7.jpg" />
          {articles.map((article) => (
            <Villa key={article._id} id={article._id} name={article.nom} prix={article.prix} photo={`http://les2api.30d7d9e7b2014052a7b4.francecentral.aksapp.io/media/${article.image}`} adresse={"test"}></Villa>
          ))}
        </div>
        <div className={styles.grid}>
          {/* <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Villa 1 &rarr;</h2>
            <img className={styles.img} src="https://i.pinimg.com/originals/f1/7a/09/f17a09db50bc69d3ae1708b1bf2ccb87.png"></img>
          </a> */}

          {/* <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Villa 2 &rarr;</h2>
            <img className={styles.img} src="https://i.pinimg.com/originals/f1/7a/09/f17a09db50bc69d3ae1708b1bf2ccb87.png"></img>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Villa 3 &rarr;</h2>
            <img className={styles.img} src="https://i.pinimg.com/originals/f1/7a/09/f17a09db50bc69d3ae1708b1bf2ccb87.png"></img>
          </a> */}
        </div>
      </main>


    </div>
  )
}
type article = {
  _id: string
  nom: string
  prix: string
  image: string
}
type response = {
  message: string
  data: {
    articles: article[]
  }
}
export async function getStaticProps() {
  const res = await fetch('http://les2api.30d7d9e7b2014052a7b4.francecentral.aksapp.io/article')
  const { data }: response = await res.json()
  const { articles } = data
  return {
    props: {
      articles,
    },
    revalidate: 10,
  }
}
export default Home
